import { Download } from "lucide-react";
import ResourcePage from "../components/common/ResourcePage";
import { api } from "../lib/api";

export default function ReportsPage() {
  return (
    <ResourcePage
      title="Reports"
      subtitle="Generated audit and compliance reports"
      resource="reports"
      searchKeys={["code", "title", "period", "generatedBy"]}
      filters={[
        {
          key: "status",
          label: "Status",
          values: ["Draft", "Final", "Approved"],
        },
        {
          key: "type",
          label: "Type",
          values: ["Audit Summary", "Compliance", "Risk", "CAPA", "Findings"],
        },
      ]}
      fields={[
        { key: "code", label: "ID", hiddenInTable: true },
        { key: "title", label: "Title", required: true },
        {
          key: "type",
          label: "Type",
          options: ["Audit Summary", "Compliance", "Risk", "CAPA", "Findings"],
          required: true,
        },
        {
          key: "generatedBy",
          label: "Generated By",
          required: true,
          selectResource: "users",
        },
        { key: "generatedDate", label: "Generated Date", type: "date" },
        { key: "period", label: "Period", required: true },
        {
          key: "status",
          label: "Status",
          options: ["Draft", "Final", "Approved"],
        },
        { key: "pages", label: "Pages", type: "number" },
        {
          key: "file",
          label: "Report File",
          type: "file",
          accept: ".pdf,.doc,.docx,.xls,.xlsx,.png,.jpg,.jpeg",
          hiddenInTable: true,
        },
      ]}
      rowActions={(row) =>
        row.fileName ? (
          <button
            type="button"
            onClick={() =>
              api.download(`/reports/${row._id}/download`, row.fileName)
            }
            className="p-2 text-slate-400 hover:text-ink-700 rounded"
            title="Download report"
          >
            <Download className="w-4 h-4" />
          </button>
        ) : null
      }
    />
  );
}
