import React, { useEffect, useMemo, useState } from 'react';
import PageHeader from './PageHeader';
import Badge from './Badge';
import Button from './Button';
import { Pencil, Plus, Search, Trash2, X } from 'lucide-react';
import { resourceApi } from '../../lib/api';

type Field = { key: string; label: string; type?: string; required?: boolean; options?: string[]; selectResource?: string; selectLabel?: string; placeholder?: string; hiddenInTable?: boolean; hiddenInForm?: boolean; multiline?: boolean };

type Props = { title: string; subtitle: string; resource: string; fields: Field[]; searchKeys: string[]; filters?: { key: string; label: string; values: string[] }[]; transform?: (row:any)=>any; canDelete?: boolean; canCreate?: boolean; renderCell?: (row:any, field:Field)=>React.ReactNode };

const display = (v:any) => typeof v === 'object' && v ? (v.name || v.title || v.code || '—') : (v ?? '—');

export default function ResourcePage({ title, subtitle, resource, fields, searchKeys, filters = [], transform = x=>x, canDelete=true, canCreate=true, renderCell }: Props) {
  const [rows,setRows]=useState<any[]>([]); const [search,setSearch]=useState(''); const [filter,setFilter]=useState<Record<string,string>>({});
  const [loading,setLoading]=useState(true); const [selectOptions,setSelectOptions]=useState<Record<string,any[]>>({}); const [error,setError]=useState(''); const [editing,setEditing]=useState<any|null>(null); const [saving,setSaving]=useState(false);
  const api = useMemo(()=>resourceApi(resource),[resource]);
  const load=async()=>{setLoading(true);setError('');try{const r=await api.list('limit=100&sort=-createdAt');setRows(r.data||[]);}catch(e:any){setError(e.message)}finally{setLoading(false)}};
  useEffect(()=>{load()},[resource]);
  useEffect(()=>{ const targets=fields.filter(f=>f.selectResource); Promise.all(targets.map(async f=>{try{const r=await resourceApi(f.selectResource!).list('limit=100');return [f.key,r.data||[]] as const}catch{return [f.key,[]] as const}})).then(xs=>setSelectOptions(Object.fromEntries(xs))) },[resource]);
  const filtered=rows.filter(row=>{const q=search.toLowerCase(); const okSearch=!q||searchKeys.some(k=>String(display(row[k])).toLowerCase().includes(q)); const okFilters=filters.every(f=>!filter[f.key]||filter[f.key]==='All'||String(display(row[f.key]))===filter[f.key]);return okSearch&&okFilters});
  const submit=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);setError('');const form=new FormData(e.currentTarget as HTMLFormElement);const body:any={};fields.forEach(f=>{const v=form.get(f.key);if(v!==null&&v!=='')body[f.key]=v});fields.filter(f=>f.type==='number').forEach(f=>{if(body[f.key]!==undefined)body[f.key]=Number(body[f.key])});try{if(editing?.mode==='edit')await api.update(editing._id,body);else await api.create(body);setEditing(null);await load()}catch(e:any){setError(e.message)}finally{setSaving(false)}};
  const remove=async(id:string)=>{if(!confirm('Delete this record? This action cannot be undone.'))return;try{await api.remove(id);setRows(r=>r.filter(x=>x._id!==id))}catch(e:any){setError(e.message)}};
  return <div><PageHeader title={title} subtitle={subtitle} action={canCreate?<Button icon={<Plus className="w-4 h-4"/>} onClick={()=>setEditing({mode:'create'})}>New</Button>:undefined}/>
    {error&&<div className="mb-4 p-3 rounded-lg bg-red-50 border border-red-200 text-sm text-red-700">{error}</div>}
    <div className="flex flex-col md:flex-row gap-3 mb-5"><div className="relative flex-1 max-w-sm"><Search className="absolute left-3 top-1/2 -translate-y-1/2 w-4 h-4 text-slate-400"/><input value={search} onChange={e=>setSearch(e.target.value)} placeholder={`Search ${title.toLowerCase()}…`} className="w-full pl-9 pr-3 py-2 text-sm bg-white border border-slate-300 rounded-lg"/></div>{filters.map(f=><select key={f.key} value={filter[f.key]||'All'} onChange={e=>setFilter({...filter,[f.key]:e.target.value})} className="px-3 py-2 text-sm bg-white border border-slate-300 rounded-lg"><option>All</option>{f.values.map(v=><option key={v}>{v}</option>)}</select>)}</div>
    <div className="bg-white rounded-xl border border-slate-200 shadow-sm overflow-hidden"><div className="overflow-x-auto"><table className="w-full text-sm"><thead><tr className="text-left text-xs text-slate-500 bg-slate-50 border-b border-slate-200">{fields.filter(f=>!f.hiddenInTable).map(f=><th key={f.key} className="px-4 py-3 font-medium">{f.label}</th>)}<th className="px-4 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y divide-slate-100">{loading?<tr><td colSpan={fields.length+1} className="p-10 text-center text-slate-400">Loading…</td></tr>:filtered.map(row=><tr key={row._id} className="hover:bg-slate-50">{fields.filter(f=>!f.hiddenInTable).map(f=><td key={f.key} className="px-4 py-3 text-slate-600">{renderCell?renderCell(row,f):(['status','severity','level','priority','role','type'].includes(f.key)?<Badge label={display(row[f.key])}/>:display(row[f.key]))}</td>)}<td className="px-4 py-3"><div className="flex justify-end gap-1"><button onClick={()=>setEditing({...row,mode:'edit'})} className="p-2 text-slate-400 hover:text-ink-700 rounded"><Pencil className="w-4 h-4"/></button>{canDelete&&<button onClick={()=>remove(row._id)} className="p-2 text-slate-400 hover:text-red-600 rounded"><Trash2 className="w-4 h-4"/></button>}</div></td></tr>)}{!loading&&!filtered.length&&<tr><td colSpan={fields.length+1} className="p-10 text-center text-slate-400">No records found.</td></tr>}</tbody></table></div></div>
    {editing&&<div className="fixed inset-0 z-50 bg-black/40 flex items-center justify-center p-4"><form onSubmit={submit} className="w-full max-w-2xl max-h-[90vh] overflow-y-auto bg-white rounded-2xl shadow-2xl"><div className="flex items-center justify-between px-5 py-4 border-b"><div><h2 className="font-semibold text-slate-900">{editing.mode==='edit'?'Edit':'Create'} {title.replace(/s$/,'')}</h2><p className="text-xs text-slate-500 mt-0.5">Changes are saved directly to MongoDB.</p></div><button type="button" onClick={()=>setEditing(null)}><X className="w-5 h-5 text-slate-400"/></button></div><div className="p-5 grid grid-cols-1 md:grid-cols-2 gap-4">{fields.filter(f=>!f.hiddenInForm && f.key !== 'code').map(f=><div key={f.key} className={f.multiline?'md:col-span-2':''}><label className="block text-xs font-medium text-slate-600 mb-1">{f.label}</label>{(f.options||f.selectResource)?<select name={f.key} defaultValue={editing.mode==='edit'?(editing[f.key]?._id || editing[f.key] || ''):''} required={f.required} className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg"><option value="">Select…</option>{f.options?.map(o=><option key={o} value={o}>{o}</option>)}{selectOptions[f.key]?.map(o=><option key={o._id} value={o._id}>{f.selectLabel?o[f.selectLabel]:o.name}</option>)}</select>:f.multiline?<textarea name={f.key} defaultValue={display(editing[f.key])} required={f.required} rows={4} className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg"/>:<input name={f.key} defaultValue={editing.mode==='edit'?(typeof editing[f.key]==='string'?editing[f.key]:display(editing[f.key])):''} type={f.type||'text'} required={f.required && !(editing.mode==='edit' && f.key==='password')} placeholder={f.placeholder} className="w-full px-3 py-2 text-sm border border-slate-300 rounded-lg"/>}</div>)}</div><div className="px-5 py-4 border-t flex justify-end gap-2"><Button type="button" variant="secondary" onClick={()=>setEditing(null)}>Cancel</Button><Button type="submit" disabled={saving}>{saving?'Saving…':'Save'}</Button></div></form></div>}
  </div>
}
