import React from 'react';
import PageHeader from '../components/common/PageHeader';
import Badge from '../components/common/Badge';
import Button from '../components/common/Button';
import { reports } from '../data/reportsData';
import { Download, Plus, FileText } from 'lucide-react';

const ReportsPage: React.FC = () => (
  <div>
    <PageHeader
      title="Reports"
      subtitle={`${reports.length} reports generated`}
      action={<Button icon={<Plus className="w-4 h-4" />}>Generate Report</Button>}
    />

    <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-4">
      {reports.map((r) => (
        <div key={r.id} className="bg-white rounded-xl border border-slate-200 shadow-sm p-5 hover:shadow-md transition-shadow">
          <div className="flex items-start justify-between mb-3">
            <div className="w-10 h-10 rounded-lg bg-ink-500/10 flex items-center justify-center">
              <FileText className="w-5 h-5 text-ink-700" />
            </div>
            <Badge label={r.status} />
          </div>
          <h3 className="text-sm font-semibold text-slate-800 mb-1 leading-snug">{r.title}</h3>
          <p className="text-xs text-slate-500 mb-3">
            {r.type} · {r.period} · {r.pages} pages
          </p>
          <div className="border-t border-slate-100 pt-3 flex items-center justify-between">
            <div>
              <p className="text-[10px] text-slate-400">Generated by</p>
              <p className="text-xs font-semibold text-slate-700">{r.generatedBy}</p>
              <p className="text-[10px] text-slate-400">{r.generatedDate}</p>
            </div>
            <button className="p-2 rounded-lg text-slate-400 hover:text-ink-700 hover:bg-ink-500/10 transition-colors">
              <Download className="w-4 h-4" />
            </button>
          </div>
        </div>
      ))}
    </div>
  </div>
);

export default ReportsPage;
